### PR TITLE
feat: override k8s-app if set as k8sAppLabelOverride

### LINKED ISSUE #19: Support custom k8s-app label on cluster service installation
Hi there! 👋

TL;DR:
I would like to override the `k8s-app` label to `kube-dns` rather than `coredns` when installing this Chart in cluster service mode (`isClusterService` enabled). However, actually there is no way to change that since it's pointing to the Chart name - as shown below.

https://github.com/coredns/helm/blob/c4e1c9936688c6257993c2d3c4472b2ffebf75b4/stable/coredns/templates/deployment.yaml#L10

https://github.com/coredns/helm/blob/c4e1c9936688c6257993c2d3c4472b2ffebf75b4/stable/coredns/templates/service.yaml#L24

Context:

I've used kOps to configure and launch my Kubernetes clusters so far. When provisioning the cluster, kOps determines the cluster DNS IP address (e.g. based on pod's overlay network) and handover it to nodes (over the `--cluster-dns` parameter on kubelet) and it creates a `kube-dns` Service in the cluster with a fixed `clusterIP` address as well.

Now, I would like to use the official CoreDNS Helm Chart and replace the KubeDNS one. However, I want to do this by preserving the old `kube-dns` Service to be able to avoid any outage on apps (regarding DNS resolutions, for sure 🙈). Since the selector is an immutable field in the Service spec, I can't change it to accord with the CoreDNS one (`k8s-app==coredns`). So, I would like to be able to override the `k8s-app` label. 😬

### PR DESCRIPTION
**Pull request by GenPage**
builds off of #52 and closes #19

### CODE REVIEW

**Comment by GenPage** [comment]
@mrueg I implemented your suggestion in #52 here to template the k8sapplabel in _helpers.

**Comment by GenPage** [comment]
I re-worked the PR, there was too much complexity with trying to manipulate customLabels to not duplicate the "k8s-app" label if its set in CustomLabels during my integration testing so I just simplified the logic for now with a new key in values.yaml.

**Comment by varkey** [comment]
It might be helpful to add a reference to the new key (ie `k8sAppLabelOverride`) in the [values.yaml](https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml). Also, a comment indicating that changing the value post deploy won't work cause the selector labels are [immutable](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates). 

As a manual step, the below can be done though. Followed by deleting the now orphaned replicaset. 

`kubectl delete deployment coredns --cascade=orphan`

**Comment by shamil** [comment]
@mrueg @haad is this planned to be merged? We are blocked until this this change is released, we need it to be able to replace `kube-dns` on existing clusters.

**Comment by kahirokunn** [comment]
I have same problem.

**Comment by kahirokunn** [comment]
@GenPage Can you fix lint errors?

**Comment by GenPage** [comment]
I will address all comments this week. Just got back from KubeCon.

**Comment by kahirokunn** [comment]
LGTM

**Comment by GenPage** [comment]
Fixed lint errors, I didn't have `ct` properly configured locally. It was a single trailing space.

**Pull request merged**
