### PR TITLE
feat: add support daemonset

### PR DESCRIPTION
**Pull request by clwluvw**
Signed-off-by: Seena Fallah <seenafallah@gmail.com>

### CODE REVIEW

**Comment by clwluvw** [comment]
ping @mrueg

**Comment by psvmcc** [comment]
ping @mrueg

**Comment by azelezni** [comment]
Any update on this?
It'll be very useful to be able to run coredns as a DaemonSet.

**Comment by HagaiBarel** [comment]
Hi, if the suggested change is for running CoreDNS as a local node dns, please be aware that that use case isn't supported by upstream CoreDNS and neither in this chart (see https://github.com/coredns/coredns/issues/4082#issuecomment-679133275)

**Comment by clwluvw** [comment]
> Hi, if the suggested change is for running CoreDNS as a local node dns, please be aware that that use case isn't supported by upstream CoreDNS and neither in this chart (see [coredns/coredns#4082 (comment)](https://github.com/coredns/coredns/issues/4082#issuecomment-679133275))

@HagaiBarel In my scenario, it's not. I just wanted to have coredns on all nodes for my setup (basically it was a small setup so it makes sense).

**Comment by HagaiBarel** [comment]
I've been giving this a lot of thought and I don't think this is a use case we should support, for a couple of reasons:
* We already provide configuration options for autoscaling using the `autoscaler` api and `cluster-proportional-autoscaler` 
* A daemonset doesn't support rolling upgrades and as such could lead to service disruptions
* The best way to achieve a local (e.g per Node) DNS service should be using [node local dns](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/), this isn't what this chart is about

**Comment by azelezni** [comment]
I've actually tested running coredns as daemonset and got pretty bad results (at least with default config), so I created a version if this chart to run both coredns deployment and node-local-dns daemonset, and now we pretty much eliminated all dns issues and don't have to worry about scaling.

@HagaiBarel  I can create a PR is this is something you'd like to support.

**Comment by HagaiBarel** [comment]
Thanks @azelezni for the inputs and suggestion but `node-local-dns` is really out of scope of this chart (and upstream `coredns` in general)

**Pull request closed without merging**
