### PR TITLE
Allow passing custom arguments to the autoscaler

### PR DESCRIPTION
**Pull request by sarahhodne**
This can be useful if you have CoreDNS deployments that only serve a subset of nodes, and you want to use --nodelabels on the autoscaler to have it scale according to just those nodes.

For example, we have a canary deployment of CoreDNS that is configured to be the cluster resolver for a subset of our Kubernetes nodes. Currently we have cluster-proportional-autoscaler enabled for both the canary deployment and the non-canary deployment, but since the canary deployment only serves about a tenth of the number of nodes, it's effectively very overprovisioned.

Tested using `helm template` to make sure the output looked correct and was indented as expected.

### CODE REVIEW

**Comment by mrueg** [comment]
Please bump the chart version as well, thanks!

**Comment by sarahhodne** [comment]
What's your versioning policy, is this a minor update (since it adds a new feature) or a patch update (which seems to be what most updates are in this repo)?

**Comment by mrueg** [comment]
ideally it would be a minor release, admitting that I am not super strict about it.

**Comment by sarahhodne** [comment]
Bumped to 1.17.0

**Pull request merged**
