### PR TITLE
Allow k8s-app label to be overridden

### LINKED ISSUE #19: Support custom k8s-app label on cluster service installation
Hi there! 👋

TL;DR:
I would like to override the `k8s-app` label to `kube-dns` rather than `coredns` when installing this Chart in cluster service mode (`isClusterService` enabled). However, actually there is no way to change that since it's pointing to the Chart name - as shown below.

https://github.com/coredns/helm/blob/c4e1c9936688c6257993c2d3c4472b2ffebf75b4/stable/coredns/templates/deployment.yaml#L10

https://github.com/coredns/helm/blob/c4e1c9936688c6257993c2d3c4472b2ffebf75b4/stable/coredns/templates/service.yaml#L24

Context:

I've used kOps to configure and launch my Kubernetes clusters so far. When provisioning the cluster, kOps determines the cluster DNS IP address (e.g. based on pod's overlay network) and handover it to nodes (over the `--cluster-dns` parameter on kubelet) and it creates a `kube-dns` Service in the cluster with a fixed `clusterIP` address as well.

Now, I would like to use the official CoreDNS Helm Chart and replace the KubeDNS one. However, I want to do this by preserving the old `kube-dns` Service to be able to avoid any outage on apps (regarding DNS resolutions, for sure 🙈). Since the selector is an immutable field in the Service spec, I can't change it to accord with the CoreDNS one (`k8s-app==coredns`). So, I would like to be able to override the `k8s-app` label. 😬

### PR DESCRIPTION
**Pull request by samcday**
closes #19

### CODE REVIEW

**Review by frankbranham — APPROVED** [review]

**Comment by hadican** [comment]
This PR is awesome! Thanks for the support. 🥳  When will it be merged?

**Comment by samcday** [comment]
It appears @frankbranham approved them some time ago, but I'm unsure what needs to happen next for the changes to get merged or released :)

**Comment by mrueg** [comment]
I think it would be better to add this to https://github.com/coredns/helm/blob/master/charts/coredns/templates/_helpers.tpl and then use a coredns.k8sapplabel variable

**Comment by blegros-exte** [comment]
Anything new on this topic ? We already are in June and nothing moved here. Is there a reason why this is taking so long ?

**Comment by GenPage** [comment]
@samcday Are you able to implement @mrueg suggestion?

**Comment by samcday** [comment]
I could, but I personally don't see any advantage to this proposed change, so I won't :D If such a change is necessary to get this PR over the line, I certainly encourage someone to carry the torch though!

**Comment by GenPage** [comment]
No worries, completely understandable :) Thank you for the response.

**Comment by mrueg** [comment]
Closed via https://github.com/coredns/helm/pull/77

**Pull request closed without merging**
