### PR TITLE
feat: support changing the chart name in the resources

### PR DESCRIPTION
**Pull request by nettoclaudio**
This PR makes possible override the chart name by setting the field `nameOverride`.

Fixes: #19

### CODE REVIEW

**Comment by haad** [comment]
Can you bump Chart version so we can release it ?

**Comment by nettoclaudio** [comment]
Yes, I do... give a few seconds.

**Comment by iAnomaly** [comment]
@nettoclaudio Can you not do this with `fullnameOverride` value? See https://github.com/coredns/helm/blob/master/stable/coredns/templates/_helpers.tpl#L13

**Comment by nettoclaudio** [comment]
> @nettoclaudio Can you not do this with `fullnameOverride` value? See https://github.com/coredns/helm/blob/master/stable/coredns/templates/_helpers.tpl#L13

No, I can't. For backward compatibility reasons, I must preserve the `k8s-app` label as default value pointing out to `coredns` rather than `coredns-coredns` which is the default value of `fullnameOverride`.

**Comment by zouyee** [comment]
this pr need rebase.

**Comment by samuel-form3** [comment]
@nettoclaudio can you rebase it ? :) I really need this

**Comment by hadican** [comment]
@nettoclaudio I think this will solve CoreDNS installation on GKE. Could you please rebase/merge when you have time? 🥺

**Comment by nettoclaudio** [comment]
Sorry for taking so long to rebase it folks :see_no_evil:

**Comment by marinoborges** [comment]
@nettoclaudio, also needing this feature. Are you able to rebase it and solve the conflicts please?

**Comment by HagaiBarel** [comment]
Hi, this PR is fairly old and I believe most of the required changes have already been introduced to the chart at some point or another. 
I'm going to close this PR, but feel free to re-open it if it's still needed

**Pull request closed without merging**
